name: Sincronizar Conta Azul para Looker

on:
  schedule:
    - cron: '0 9 * * *' 
  workflow_dispatch: 

# Resolve o aviso do Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: |
          pip install pandas requests gspread oauth2client

      - name: Verificar Segredos
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          CONTA_AZUL_CLIENT_ID: ${{ secrets.CONTA_AZUL_CLIENT_ID }}
        run: |
          if [ -z "$GOOGLE_SHEETS_JSON" ]; then echo "❌ Erro: GOOGLE_SHEETS_JSON não configurado"; exit 1; fi
          echo "✅ Segredos detectados."

      - name: Rodar Script
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          CONTA_AZUL_CLIENT_ID: ${{ secrets.CONTA_AZUL_CLIENT_ID }}
          CONTA_AZUL_CLIENT_SECRET: ${{ secrets.CONTA_AZUL_CLIENT_SECRET }}
        # O comando abaixo ajuda a mostrar erros mais detalhados
        run: python app.py
